### ISSUE TITLE
Problème avec l'affichage des données

### ISSUE THREAD

**Issue by snooze06** [kepon85/PvMonit#6]
Bonjour,

Merci pour le travail accompli, car étant en total autonomie, votre PvMonit est parfaitement adapté.
Mais, ( il en faut un,) j'arrivai à faire tourner la version 0.8, mais je tombe sur une erreur avec la 1.0 que je n'arrive pas à solutionner.
Récupération des données OK, via le controle vedirect.py
La page index.php s'affiche, mais pas de données, juste le cadre divers qui reste vide.
en analysant le log /var/log/lighttpd/error.log, voici les erreurs :

2019-11-24 20:21:05: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  Use of undefined constant VEDIRECT_BIN - assumed 'VEDIRECT_BIN' (this will throw an Error in a future version of PHP) in /opt/PvMonit/function.php on line 375

2019-11-24 20:21:05: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined variable: vedirect_scan_return in /opt/PvMonit/function.php on line 452

2019-11-24 20:21:05: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  Invalid argument supplied for foreach() in /opt/PvMonit/www/data-xml.php on line 68

à chaque rafraichissement de la page, toujours les mêmes.
Si vous avez une piste, ou s'il vous faut plus d'info ...
par avance merci
Nico

**Comment by kepon85** [comment]
Bonjour Nico,

ça n'a pas a voir avec la ce que tu as trouvé dans le log je pense.

Récupère la dernière version de PvMonit (juste envoyé) notamment pour ces 3 premières lignes : https://github.com/kepon85/PvMonit/blob/master/www/data-xml.php#L2

Dans ton fichier config.yaml ajoute :
printMessage: 5                         # 0=0	5=debug
printMessageLogfile: /tmp/PvMonit-debug.log              # path or fase

Tente d'afficher la page et envoi le contenu du fichier /tmp/PvMonit-debug.log + le log lighttpad que tu as trouvé plus haut.

David

**Comment by snooze06** [comment]
Bonjour David,
Merci de ton retour.
J'ai remplacé data-xml.php par celui de ton lien

voici le log de PvMonit-debug.log
2019-11-25T15:15:20+00:00 - /data-xml.php - Appel du data-xml.php
2019-11-25T15:15:20+00:00 - /data-xml.php - Recherche de périphérique vedirect
2019-11-25T15:15:20+00:00 - /data-xml.php - Un périphérique TTY à été trouvé : ttyUSB0
2019-11-25T15:15:21+00:00 - /data-xml.php - Erreur à l'exécution du script VEDIRECT_BIN sur le ttyUSB0
2019-11-25T15:15:21+00:00 - /data-xml.php - Scan du répertoire bin-enable
2019-11-25T15:15:21+00:00 - /data-xml.php - Fin du data-xml.php

et log de lighttpd/error.log

2019-11-25 15:15:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  Use of undefined constant VEDIRECT_BIN - assumed 'VEDIRECT_BIN' (this will throw an Error in a future version of PHP) in /opt/PvMonit/function.php on line 375
2019-11-25 15:15:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined variable: vedirect_scan_return in /opt/PvMonit/function.php on line 452
2019-11-25 15:15:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  Invalid argument supplied for foreach() in /opt/PvMonit/www/data-xml.php on line 66

Ce qui correspond bien à l'erreur de lancement du script et à la ligne 375 de function.php (la ligne 452 étant la sortie de la fonction)

Je n'ai pas mis le log entier, mais juste erreur avec l'ancien fichier data-xml et le nouveau, car toujours pareil sauf changement de ligne 68 à 66.

[log erreur lighttpd.log](https://github.com/kepon85/PvMonit/files/3887472/log.erreur.lighttpd.log)

merci
Nico

**Comment by kepon85** [comment]
Est-ce que tu as bien configuré "sudo" ? : https://github.com/kepon85/PvMonit/blob/master/INSTALL.md#vedirect-via-usb (à partir de la commande visudo)

Poste moi le fichier de conf : /etc/sudoers

La commande suivante, lancé en root, ne doit pas te demandé de mot de passe et doit te renvoyer les information vedirect si tu as bien configuré sudo : 

`su - www-data -s /bin/bash -c "sudo /opt/PvMonit/bin/vedirect.py /dev/tty0"`

As-tu bien installé toute la "base" ? https://github.com/kepon85/PvMonit/blob/master/INSTALL.md#la-base--le-socle (dont python-serial)

**Comment by snooze06** [comment]
bonjour david,

oui j'ai relancé l'install de la base et zéro action.
oui sudo paramétré, fichier joint de sudoers.
[cat de sudoers.txt](https://github.com/kepon85/PvMonit/files/3890930/cat.de.sudoers.txt)

par contre la cde su-ww-data en mode root, génére des erreurs. je crois que tu as mis le doigt dessus...
fichier joint 
[erreur suite cde su - www-data.txt](https://github.com/kepon85/PvMonit/files/3890935/erreur.suite.cde.su.-.www-data.txt)
alors que la cde /opt/PvMonit/bin/vedirect.py /dev/ttyUSB0 fonctionne en mode users..

**Comment by snooze06** [comment]
mince
j'ai oublié de te joindre la sortie de /opt/PvMonit/bin/vedirect.py /dev/tty0 en mode users
[cat sortie vedirect.py mode users.txt](https://github.com/kepon85/PvMonit/files/3891031/cat.sortie.vedirect.py.mode.users.txt)

**Comment by kepon85** [comment]
Wow, très étrange...
Du coup c'est pas sudo qui est en cause.

Peut être un problème de droit sur ttyUSB0, chez moi /dev/ttyUSB0 à les droits suivant: 
```
root@raspberrypi(rw):~# ls -la /dev/ttyUSB0 
crw-rw---- 1 root dialout 188, 0 Nov 26 12:28 /dev/ttyUSB0
```
C'est le groupe dialout qui a les droits dessus, si c'est pareil pour toi tente cette commande  : 

`usermod -G dialout www-data`

Redémarre ton raspberry et test de nouveau la commande 

`su - www-data -s /bin/bash -c "sudo /opt/PvMonit/bin/vedirect.py /dev/tty0"`

Si jamais ça ne fonctionne pas, on tente plus bourrin : 

`chmod 777 /dev/ttyUSB0`

Et relance la commande "su -..." pour voir...
Dit moi...

**Comment by snooze06** [comment]
bon , pour les droits sur /dev/ttyusb0, idem que toi

voici le résultat de la séquence après Usermod -G et reboot

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# su - www-data -s /bin/bash -c "sudo /opt/PvMonit/bin/vedirect.py /dev/tty0"
Traceback (most recent call last):
  File "/opt/PvMonit/bin/vedirect.py", line 84, in <module>
    ve.read_data_single()
  File "/opt/PvMonit/bin/vedirect.py", line 78, in read_data_single
    packet = self.input(byte)
  File "/opt/PvMonit/bin/vedirect.py", line 34, in input
    self.bytes_sum += ord(byte)
TypeError: ord() expected a character, but string of length 0 found
root@raspberrypi:/home/pi# exit
exit
pi@raspberrypi:~ $ su - www-data -s /bin/bash -c "sudo /opt/PvMonit/bin/vedirect.py /dev/tty0"
Password: 
su: Authentication failure
pi@raspberrypi:~ $ chmod 777 /dev/ttyUSB0
chmod: changing permissions of '/dev/ttyUSB0': Operation not permitted
pi@raspberrypi:~ $ sudo chmod 777 /dev/ttyUSB0
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# su - www-data -s /bin/bash -c "sudo /opt/PvMonit/bin/vedirect.py /dev/tty0"
Traceback (most recent call last):
  File "/opt/PvMonit/bin/vedirect.py", line 84, in <module>
    ve.read_data_single()
  File "/opt/PvMonit/bin/vedirect.py", line 78, in read_data_single
    packet = self.input(byte)
  File "/opt/PvMonit/bin/vedirect.py", line 34, in input
    self.bytes_sum += ord(byte)
TypeError: ord() expected a character, but string of length 0 found
root@raspberrypi:/home/pi# 

root@raspberrypi:/home/pi# ls -la /dev/ttyUSB0 
crwxrwxrwx 1 root dialout 188, 0 Nov 26 15:34 /dev/ttyUSB0
root@raspberrypi:/home/pi# 
si j'ai bien compris ton prog, la lecture se fait direct sur ttysub0 et envoi dans un tableau?

**Comment by kepon85** [comment]
Est-ce que tu as ré-installé depuis la version 0.8 ? (tu me disais que ça fonctionnai avec elle)
Parce que c'est étrange, cette partie là n'a pas bougé depuis la version 0.8... C'est le même script : https://github.com/kepon85/PvMonit/commits/master/bin/vedirect.py
C'est d'autant plus troublant qu'avec le user "pi" ça fonctionne d'après ce que tu m'as envoyé !?
Je sèche un peu là, est-ce que tu peux me contacter par mail pour qu'on envisage une prise de main à distance si tu veux bien : https://david.mercereau.info/contact/

**Comment by snooze06** [comment]
David,
je viens de refaire des essais et j'ai avancé,
Dans la ligne de cde que tu m'as demandé de testé, en mode root
su - www-data -s /bin/bash -c "sudo /opt/PvMonit/bin/vedirect.py /dev/tty0"

j'ai remplacé tty0 par ttyUSB0 et voici le résultat.
[Essai avec ttyUSB0 au lieu de tty0.txt](https://github.com/kepon85/PvMonit/files/3896556/Essai.avec.ttyUSB0.au.lieu.de.tty0.txt)
Bon reste à savoir pourquoi tty0 ne veut pas fonctionner, car ton code doit être écrit avec tty0 je suppose.

**Comment by kepon85** [comment]
Haaa mais effectivement tty0 n'existe pas, c'est bien ttyUSB0 :-/ (pardon... faute de frappe ça coûte chère parfois...)

Et bien maintenant il y a quoi dans le log PvMonit-debug.log quand tu va sur la page web ? c.f. mon message plus haut pour l'activer dans le fichier de conf...

**Comment by kepon85** [comment]
Je crois que je viens de comprendre. Le script vedirect est appelé par "/usr/bin/sudo /usr/bin/python /opt/PvMonit/bin/vedirect.py" et dans ma doc d'install je fais mettre "/opt/PvMonit/bin/vedirect.py" dans le fichier sudo... ça ne peut donc pas fonctionner. Donc j'ai corrigé ça : https://github.com/kepon85/PvMonit/blob/master/INSTALL.md#vedirect-via-usb Met dans ton fichier sudo : 

`www-data ALL=(ALL) NOPASSWD:/usr/bin/python /opt/PvMonit/bin/vedirect.py *`

Et non pas 

`www-data ALL=(ALL) NOPASSWD:/opt/PvMonit/bin/vedirect.py *`

Je penses que c'est ça... donne moi des nouvelles !

**Comment by kepon85** [comment]
Et re-télécharge le contenu du dépôt GIT (ici même)
J'ai mis à jour notamment 	function.php et www/data-xml.php et ça devrait t'éviter de nouveau problèmes :-)

**Comment by snooze06** [comment]
bon, on avance, le log est plus bavard qu'avant, mais pas encore d'affichage.

2019-11-27T17:31:32+00:00 - /data-xml.php - Appel du data-xml.php
2019-11-27T17:31:32+00:00 - /data-xml.php - Recherche de périphérique vedirect
2019-11-27T17:31:32+00:00 - /data-xml.php - Un périphérique TTY à été trouvé : ttyUSB0
2019-11-27T17:31:33+00:00 - /data-xml.php - C'est un BMV, modèle "Inconnu" du nom de 712 Smart
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H1:-2121606
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H2:-272405
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H3:-78131
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H4:172
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H5:4
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H6:-134416817
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H7:26
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H8:59303
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H9:97601
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H10:318
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H11:0
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H12:0
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H15:24
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H16:21005
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H17:644753
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : H18:540355
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : V:46413
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : VS:33
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : I:-11944
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : P:-554
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : CE:-249970
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : SOC:676
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : TTG:693
2019-11-27T17:31:33+00:00 - /data-xml.php - Valeur trouvé : AR:0
2019-11-27T17:31:33+00:00 - /data-xml.php - Les données sont formatées comme ceci : H1:-2121606,H2:-272405,H3:-78131,H4:172,H5:4,H6:-134416817,H7:26,H8:59303,H9:97601,H10:318,H11:0,H12:0,H15:24,H16:21005,H17:644753,H18:540355,V:46413,VS:33,I:-11944,P:-554,CE:-249970,SOC:676,TTG:693,AR:0
2019-11-27T17:31:33+00:00 - /data-xml.php - Scan du répertoire bin-enable
2019-11-27T17:31:33+00:00 - /data-xml.php - Fin du data-xml.php
2019-11-27T17:31:40+00:00 - /data-xml.php - Appel du data-xml.php
2019-11-27T17:31:40+00:00 - /data-xml.php - Scan du répertoire bin-enable
2019-11-27T17:31:40+00:00 - /data-xml.php - Fin du data-xml.php
2019-11-27T17:31:43+00:00 - /data-xml.php - Appel du data-xml.php
2019-11-27T17:31:43+00:00 - /data-xml.php - Scan du répertoire bin-enable
2019-11-27T17:31:43+00:00 - /data-xml.php - Fin du data-xml.php

avec les nouveaux fichiers function.php et data-xml.php

**Comment by kepon85** [comment]
Quand tu dis "pas d'affichage" tu peux m'en dire plus ? Une capture d'écran  ou au minium ce qu'il affiche (rien ? un message d'erreur ?)

Modifie ton fichier de conf (config.yaml) et change les lignes de cache par : 

```
cache:
    dir: /tmp/PvMonit_cache                 # in tmpfs
    file_prefix: 
    time: 0
```

Balance de nouveau le log de debug dans le doute...

Remplace le fichier /opt/PvMonit/www/data-xml.php par le dernier que j'ai envoyé : https://github.com/kepon85/PvMonit/blob/master/www/data-xml.php ensuite va sur http://TONIPLOCAL/data-xml.php et envoi moi le contenu du fichier...

P.S. 67% les batteries et 540W qui tire, waw t'as peur de rien toi....

**Comment by snooze06** [comment]
bonjour david,
ci-joint copie d'écran
![Capture d’écran de 2019-11-28 08-58-30](https://user-images.githubusercontent.com/58149094/69788338-96390880-11be-11ea-87d0-03e4a33f5efe.png)

ci-joint log de debug
[log de PvMonit-debug.log.txt](https://github.com/kepon85/PvMonit/files/3900567/log.de.PvMonit-debug.log.txt)

ci-joint contenu après exécution de data-xml.php
[contenu de data-xml.php.txt](https://github.com/kepon85/PvMonit/files/3900568/contenu.de.data-xml.php.txt)

PS : justement j'ai un doute sur les valeurs du bmv, car par moment étant aveugle, je n'ai pas les mêmes infos entre les deux chargeurs et le bmv sur le taux de charge et décharge. je te ferai un topo de l'installation . 

Nico

**Comment by snooze06** [comment]
david,
j'ai trouvé une anomalie dans le jquery.min.js
![Capture d’écran de 2019-11-28 17-35-50](https://user-images.githubusercontent.com/58149094/69822112-da033080-1205-11ea-9f15-08e017e57cb0.png)
ce qui bloque l'éxécution du script ici
![Capture d’écran de 2019-11-28 17-36-09](https://user-images.githubusercontent.com/58149094/69822155-f0a98780-1205-11ea-83ca-99ac39f2e56b.png)
dans le cas ou cela peut aider, car comme le XML est bon je ne vois pas pourquoi il ne être traité par le PHP!!!!
Je continue mes investigations...

**Comment by snooze06** [comment]
bon, j'ai rajouter mon BMV dans la liste, mais cela n'a eu d'incidence,
par contre dans le log de lighttpd il ya toujours c'est deux lignes

2019-11-28 19:05:27: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined variable: ve_serial in /opt/PvMonit/function.php on line 512
2019-11-28 19:05:27: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  sort() expects parameter 1 to be array, string given in /opt/PvMonit/www/data-xml.php on line 78

c'est ligne 511, car j'ai ajouté mon BMV dans la liste dans function.php

`case '0xA381': $ve_modele_retour='BMV-712 Smart'; break;`

par contre par moment avec  l'actualisation auto  j'ai un deuxième cadre qui apparait et quand je clic sur les 3 ... il s'ouvre mais avec des champs vide !!!, puis à l'actu suivante, il disparait...

**Comment by snooze06** [comment]
le titre du cadre indique inconnu...
![Capture d’écran de 2019-11-28 20-16-50](https://user-images.githubusercontent.com/58149094/69828427-20fc2080-121c-11ea-8954-cc168459eba8.png)

**Comment by snooze06** [comment]
si cela peut aider voici le log de lighttpd quand il y a une le cadre inconnu.
[log  lighttpd avec le cadre inconnu.txt](https://github.com/kepon85/PvMonit/files/3902867/log.lighttpd.avec.le.cadre.inconnu.txt)

**Comment by kepon85** [comment]
Télécharge de nouveau les sources via le dépôt git, surtout fonction.php et www/data-xml.php
J'ai réussi à reproduire ton problème en "servant" ton fichier XML à une instance pvmonit que j'utilise. En fait le BMV '712 smart' à un espace  dans son petit nom et ça, le XML ne le supportais pas dans le champs "id".
Je penses que c'est bon maintenant.
SI ce n'est pas le cas, redonne moi un max d'info

**Comment by snooze06** [comment]
Merci de ton aide, voici le résultat
![Capture d’écran de 2019-11-29 09-01-39](https://user-images.githubusercontent.com/58149094/69853367-027f3f00-1287-11ea-9cbc-dbb2bea9c379.png)

A part les caractères accentué ( un coup de UFT8 encore...) et les deux nouveaux champs H15 et 16, cela semble ok. je laisse tourné et je verrai cela lundi, car je suis en salon tout le week-end.
Envoie moi ton adresse par mail!, en remerciement, car comme  tu as oeuvré pour mon énergie solaire, je vais à mon tour t'envoyer un coup d'énergie pour toi même avec un sachet de spiruline ( je suis producteur dans le jura), c'est bon pour la mémoire et tu as en bien besoin vu comme on te solicite .....
merci encore et je te prépare un topo de mon installation, mais t'inquiéte pas la décharge est prévu jusqu'a 50%, les batteries sont prévues et calibrées pour ce seuil. (nbr de cycle de charge calculé ainsi)

**Comment by kepon85** [comment]
> A part les caractères accentué ( un coup de UFT8 encore...) et les deux nouveaux champs H15 et 16, cela semble ok. je laisse tourné et je verrai cela lundi, car je suis en salon tout le week-end.

J'ai ajouté le support des champs H15 & H16 dans la nouvelle version du fichier fonction.php

Comment tu télécharge les nouveaux fichier ? ça doit venir de là ton problème d'UTF8...

Pour être sûr et si tu n'as bien modifié que le fichier config.yaml, récupère tout les fichier du git de la façon suivante : 
```
cd /opt
# sauvegarde du tout si jamais
cp -r PvMonit /tmp 
# sauvegarde fichier de conf
cp PvMonit/config.yaml ./
rm -rf ./PvMonit
git clone https://github.com/kepon85/PvMonit.git
# Restauration de ton fichier de conf
cp ./config.yaml ./PvMonit/
```

Sinon juste le fichier function : 
```
cd /opt/PvMonit/
wget https://raw.githubusercontent.com/kepon85/PvMonit/master/function.php
```

> Envoie moi ton adresse par mail!, en remerciement, car comme tu as oeuvré pour mon énergie solaire, je vais à mon tour t'envoyer un coup d'énergie pour toi même avec un sachet de spiruline ( je suis producteur dans le jura), c'est bon pour la mémoire et tu as en bien besoin vu comme on te solicite .....

Super, merci !  Envoi moi un mail par là : https://david.mercereau.info/contact/ ou david [arobase] mercereau [poinpoint] info et je t'envoie mon adresse postale (je trouve pas comment contacter en privé par github) 

> merci encore et je te prépare un topo de mon installation, mais t'inquiéte pas la décharge est prévu jusqu'a 50%, les batteries sont prévues et calibrées pour ce seuil. (nbr de cycle de charge calculé ainsi)

Ok, généralement les descendre à 50% diminue drastiquement leur nombre de cycle, à moins que ça soit recherché ou des batteries autre que du plomb à décharge lente...

**Comment by snooze06** [comment]
Bonjour David,

Un petit message pour te remercier de nouveau pour ton travail et te donner des nouvelles. 
Effectivement en rechargeant l'ensemble des fichiers, le problème des caractères à été résolu.
J'ai réussi à renvoyé mes infos sur Jeedom, pour suivre avec précision l'état des batteries. Le monitoring est vraiement indispensable quand on est en total automonie, car j'ai pu améliorer et optimiser ma consommation. 
Maintenant que jeedom (ma domotique) reçoit l'état du BMS Victron, je peux mettre des scénarios pour envoyer le surplus de production dans la résistance du ballon d'eau chaude solaire.

Pour mes batteries ce sont des des batteries stationnaires avec électrolyte liquide (acide sulfurique dilué). des Hoppecke OPzS.
Le cycle est de 5000 décharge à 30 % ( ce qui correspond à un cycle jour/nuit du printemps à l'automne) et de 2500 à 50 % de décharge l'hiver, les journées de soleil étant plus courte.
Mon parc n'est qu'a 50 % de sa capacité pour le moment. ce qui me donne 30Kw installé pour donc 15kw dispo au maxi..
J'ai 7600 w de panneaux dont 4600w sur tracking. 2 onduleurs WKS de 5KW qui travaillent en binome.
Car quand la ferme fonctionne j'ai besoin de 5 à 6 kw la journée... et comme les wks sont des onduleurs hybrides, ils envoient l'énergie des panneaux directement dans mon réseau, le surplus va dans les batteries... mais le jour je ne tire pas sur les batteries, que la nuit.
voilà pour mon installation du moment, mais cela nous permet d'être à 100% autonome.
Bonne continuation et au plaisirs de te lire
Nicolas
